GCC = g++

OBJS = mc.o enemy.o Minotaur.o Rogueknight.o Ghost.o Skull.o Bridge.o Cave.o RuinedCity.o options.o main.o

default: Main

Main: $(OBJS)
    $(GCC) -o Main $(OBJS)

mc.o: mc.cpp mc.h 
    $(GCC) -c mc.cpp -o mc.o

enemy.o: enemy.cpp enemy.h mc.h
    $(GCC) -c enemy.cpp -o enemy.o

Minotaur.o: Minotaur.cpp Minotaur.h mc.h enemy.h
    $(GCC) -c Minotaur.cpp -o Minotaur.o

Rogueknight.o: Rogueknight.cpp Rogueknight.h mc.h enemy.h
    $(GCC) -c Rogueknight.cpp -o Rogueknight.o

Ghost.o: Ghost.cpp Ghost.h mc.h enemy.h
    $(GCC) -c Ghost.cpp -o Ghost.o

Skull.o: Skull.cpp Skull.h mc.h enemy.h
    $(GCC) -c Skull.cpp -o Skull.o

Bridge.o: Bridge.cpp Bridge.h mc.h
    $(GCC) -c Bridge.cpp -o Bridge.o

Cave.o: Cave.cpp Cave.o mc.h 
    $(GCC) -c Cave.cpp -o Cave.o

RuinedCity.o: RuinedCity.cpp RuinCity.h mc.h
    $(GCC) -c RuinedCity.cpp -o RuinedCity.o

options.o: options.cpp options.h mc.h
    $(GCC) -c options.cpp -o options.o

main.o: main.cpp mc.h enemy.h Minotaur.h Rogueknight.h Ghost.h Skull.h Bridge.h Cave.h RuinedCity.h options.h
    $(GCC) -c main.cpp -o main.o

clean:
    rm $(OBJS) Main
